### ISSUE TITLE
Redis Transport - NOSCRIPT Error when Redis Server is restarted

### ISSUE THREAD

**Issue by PeterOscarsson** [blehnen/DotNetWorkQueue#13]
Hi. 
If the Redis server gets restarted, (quite normal with Azure Redis cache) my application (that was not restarted) is experiencing errors  like
`
An exception has occurred in the monitor delegate, 
StackExchange.Redis.RedisServerException: NOSCRIPT No matching script. Please use EVAL.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2258
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.ScriptEvaluate(LoadedLuaScript script, Object parameters, CommandFlags flags) in C:\projects\stackexchange-redis\src\StackExchange.Redis\RedisDatabase.cs:line 1173
   at DotNetWorkQueue.Transport.Redis.Basic.Lua.TimeLua.Execute()
   at DotNetWorkQueue.Transport.Redis.Basic.Time.RedisServerUnixTime.GetUnixTime()
   at DotNetWorkQueue.Transport.Redis.Basic.CommandHandler.MoveDelayedRecordsCommandHandler.Handle(MoveDelayedRecordsCommand command)
   at DotNetWorkQueue.Transport.Redis.Basic.DelayedProcessingAction.Run(CancellationToken token)
   at DotNetWorkQueue.Transport.Redis.Basic.Metrics.Decorator.DelayedProcessingActionDecorator.Run(CancellationToken token)
   at DotNetWorkQueue.Transport.Redis.Basic.Logging.Decorator.DelayedProcessingActionDecorator.Run(CancellationToken token)
   at DotNetWorkQueue.Queue.BaseMonitor.RunMonitor()`

Is this something that can be fixed or can you point me in right direction to try to do a PR.

Best Regards, Peter

**Comment by blehnen** [comment]
This is an interesting one.  While there is some logic in the stackexchange redis client to handle this, it's based on being able to detect a disconnect from the client;  He cannot fully detect that the server actually restarted.

Because of that, I think the only possible fix would be to change this library to handle it.

There are a few options -

1) Make script caching optional.  This is not ideal at all, due to the size of the scripts.
2) Change each script module to handle this.  It would need to catch the exception, re-cache the script (via LoadScript) and then re-run the command.  
3) Add a decorator that performs this.  Since "BaseLua" is an abstract class, this would probably require adding interface(s) to assist in this.

On the BaseLua class, the 'LoadScript' method takes care of caching the script.  This is what would need to be called with the above failure.

I can change this, but I'm not exactly sure when I'll be able to get to this.

**Comment by PeterOscarsson** [comment]
Ok. Looks like its #2 we should implement then.  I will give it a try but as this is not a huge issue right now it will take some time for me to get to it.

**Comment by blehnen** [comment]
Alright, if I happen to get to it before you, I'll update this ticket.

**Comment by blehnen** [comment]
I was able to change this during lunch; pretty straight forward.  I have not published new assemblies to nuget yet.

**Comment by PeterOscarsson** [comment]
Gr8, and thanx.  It would have taken me a lot longer than a lunch, even though I sometimes take a long lunch. :-)
I'll look out for the new assemblies on NuGet
